config/routes.rb
Rails.application.routes.draw do
  resources :members
  devise_for :profiles, controllers: { registrations: 'profiles/registrations' }
  resources :profiles, except: [:new, :create, :show]
  get 'profiles/new', to: 'profiles#new', as: :new_profile
  post 'profiles_management', to: 'profiles#create', as: :create_profile

  resources :symptoms
  resources :medicines do
    get :activities, on: :collection
  end
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/profile.rb
class Profile < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :symptoms, dependent: :destroy
  has_many :medicines, dependent: :destroy
  has_many :members, dependent: :destroy

  enum role: { user: 0, admin: 1 }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[edit update destroy]

  def index
    @profiles = Profile.all
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to profiles_path, notice: 'Perfil criado com sucesso.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to profiles_path, notice: 'Perfil atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @profile.destroy
    redirect_to profiles_path, notice: 'Perfil excluído com sucesso.'
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:email, :name, :password, :password_confirmation, :role)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile, url: create_profile_path, html: { class: "contents" }) do |form| %>

  <div class="my-5 text-slate-900">
    <%= form.input :name, label: "Nome", input_html: { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="my-5 text-slate-900">
    <%= form.input :email, label: "Email", input_html: { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="my-5 text-slate-900">
    <%= form.input :password, label: "Senha", input_html: { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="my-5 text-slate-900">
    <%= form.input :password_confirmation, label: "Confirmar senha", input_html: { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <% if current_profile.admin? %>
    <div class="my-5 text-slate-900">
      <%= form.input :role, as: :select, collection: Profile.roles.keys.map { |role| [role == "user" ? "Usuário" : "Administrador", role] }, label: "Regra", prompt: "Selecione o tipo de acesso", required: true, input_html: { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2" }, label_html: { class: "block text-gray-700" } %>
    </div>
  <% end %>

  <div class="inline">
    <%= form.button :submit, @profile.new_record? ? "Cadastrar" : "Editar", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/profiles/_modal.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 z-50 transition-opacity duration-300 opacity-0 pointer-events-none" data-controller="modal" data-modal-target="modal" data-action="click->modal#closeWithBackdrop">
    <div class="bg-white rounded-lg overflow-hidden shadow-xl transform transition-all sm:max-w-lg sm:w-full max-h-90vh" data-modal-target="dialog" data-action="click->modal#stopPropagation">
      <div class="bg-blue-500 px-4 py-3 sm:px-6 flex justify-between items-center">
        <h5 class="text-lg leading-6 font-medium text-white"><%= title %></h5>
        <button type="button" class="text-white" data-action="modal#close" aria-label="Close">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="px-4 py-5 sm:p-6 overflow-y-auto" style="max-height: 90vh;" id="modal_body">
        <%= yield %>
      </div>
    </div>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<%= render "modal", title: "Editar perfil" do %>
  <div class="mx-auto w-full">
    <div class="bg-white">
      <%= render "form", profile: @profile %>
    </div>
  </div>
<% end %>

app/views/profiles/index.html.erb
<% content_for :title, "Perfis" %>

<div class="flex justify-between items-center mb-6">
  <h1 class="font-bold text-4xl text-blue-500">Perfis</h1>
  <%= link_to "Cadastrar perfil", new_profile_path, class: "rounded-lg py-3 px-5 bg-blue-400 hover:bg-blue-500 text-white block font-medium", data: { turbo_frame: "modal" } %>
</div>

<div id="profiles" class="w-full">
  <% if @profiles.any? %>
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-blue-50 dark:bg-gray-700">
        <tr>
          <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">Nome</th>
          <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">Email</th>
          <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">Ações</th>
        </tr>
      </thead>
      <tbody class="bg-white dark:bg-slate-700 divide-y divide-gray-200 dark:divide-gray-600">
        <% @profiles.each do |profile| %>
          <tr id="<%= dom_id profile %>">
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm dark:text-blue-50 text-gray-900"><%= profile.name %></div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm dark:text-blue-50 text-gray-900"><%= profile.email %></div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-left text-sm font-medium">
              <%= link_to edit_profile_path(profile), class: "ml-2 rounded-lg py-2 px-4 text-blue-600 hover:bg-gray-100 inline-block font-medium cursor-pointer", data: { turbo_frame: "modal" } do %>
                <%= lucide_icon('file-pen-line', class: 'inline-block text-blue-600 cursor-pointer') %>
              <% end %>
              <%= link_to profile, method: :delete, class: "ml-2 rounded-lg py-2 px-4 text-blue-600 hover:bg-gray-100 inline-block font-medium cursor-pointer", data: { turbo_method: :delete, turbo_confirm: "Tem certeza?" } do %>
                <%= lucide_icon('circle-x', class: 'inline-block text-red-600 cursor-pointer') %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Nenhum usuário registrado</p>
  <% end %>
</div>

app/views/profiles/new.html.erb
<%= render "modal", title: "Cadastrar novo perfil" do %>
  <div class="mx-auto w-full">
    <div class="bg-white">
      <%= render "form", profile: @profile %>
    </div>
  </div>
<% end %>