config/routes.rb
Rails.application.routes.draw do
  resources :members
  devise_for :profiles, controllers: { registrations: 'profiles/registrations' }
  resources :profiles, except: [:new, :create, :show]
  get 'profiles/new', to: 'profiles#new', as: :new_profile
  post 'profiles_management', to: 'profiles#create', as: :create_profile

  resources :symptoms
  resources :medicines do
    get :activities, on: :collection
  end
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  has_paper_trail

  belongs_to :profile
  
  has_many :medicine_symptoms, dependent: :destroy
  has_many :symptoms, through: :medicine_symptoms
  
  has_one_attached :picture
  has_one_attached :medicine_insert

  validates :name, :unit, :quantity, :medicine_validity, presence: true
  validate :validate_medicine_insert_attachment

  private

  def validate_medicine_insert_attachment
    if medicine_insert.attached?
      unless medicine_insert.content_type.in?(%w(application/pdf))
        errors.add(:medicine_insert, 'Deve ser em formato PDF')
        medicine_insert.purge
      end
    end
  end
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :set_medicine, only: %i[ show edit update destroy ]
  before_action :set_paper_trail_whodunnit

  def index
    if current_profile.role == "admin"
      @medicines = Medicine.all.includes([:profile, :symptoms])
    else
      @medicines = Medicine.where(profile_id: current_profile.id)
    end
  end

  def show
  end

  def new
    @medicine = Medicine.new
  end

  def edit
  end

  def create
    @medicine = current_profile.medicines.new(medicine_params)

    respond_to do |format|
      if @medicine.save
        format.turbo_stream { redirect_to medicines_url, notice: "Remédio registrado com sucesso." }
      else
        format.turbo_stream { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @medicine.update(medicine_params)
        format.turbo_stream { redirect_to medicines_url, notice: "Remédio atualizado com sucesso.", status: :see_other }
      else
        format.turbo_stream { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @medicine.destroy!
    redirect_to medicines_url, notice: "Remédio excluído com sucesso.", status: :see_other
  end

  def activities
    if current_profile.role == "admin"
      @activities = PaperTrail::Version.where(item_type: "Medicine").order(created_at: :desc)
    else
      @activities = PaperTrail::Version.where(item_type: "Medicine", whodunnit: current_profile.id.to_s).order(created_at: :desc)
    end
  end

  private

    def set_paper_trail_whodunnit
      PaperTrail.request.whodunnit = current_profile.id if current_profile
    end

    def set_medicine
      @medicine = Medicine.find(params[:id])
    end

    def medicine_params
      params.require(:medicine).permit(:picture, :name, :unit, :is_liquid, :quantity, :description, :medicine_validity, :medicine_insert, :used_to, :profile_id, symptom_ids: [])
    end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
  def format_changes(object_changes, event_type)
    if object_changes.present?
      changes_hash = object_changes.deep_symbolize_keys
      changes_html = ""

      translations = {
        name: "Nome",
        unit: "Unidade",
        is_liquid: "É líquido?",
        quantity: "Quantidade",
        medicine_validity: "Validade",
        medicine_insert: "Bula",
        used_to: "Usado para",
        created_at: "Criado em",
        updated_at: "Atualizado em",
        profile_id: "Perfil"
      }

      changes_hash.each do |attribute, values|
        translated_attribute = translations[attribute] || attribute.to_s.humanize
        before_value, after_value = values.map do |value|
          if value.is_a?(String)
            if value.match(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z/)
              Time.parse(value).strftime("%d/%m/%Y - %H:%M")
            elsif value.match(/\d{4}-\d{2}-\d{2}/)
              Date.parse(value).strftime("%d/%m/%Y")
            else
              value
            end
          else
            if attribute == :profile_id
              Profile.find_by(id: value)&.name || value
            elsif attribute == :is_liquid
              value ? "Sim" : "Não"
            else
              value
            end
          end
        end
        
        changes_html += "<strong>#{translated_attribute}:</strong><br>"
        changes_html += "<ul class='list-none'>"
        changes_html += "<li class='flex items-center space-x-2'>"

        if event_type != "create"
          changes_html += "<span class='bg-red-500 text-white px-2 py-1 rounded'>#{before_value}</span>"
        end

        if event_type == "update"
          changes_html += "<span class='text-gray-500'>=&gt;</span>"
        end

        if event_type == "create"
          changes_html += "<span class='bg-blue-300 text-white px-2 py-1 rounded'>#{after_value}</span>"
        elsif event_type != "destroy"
          changes_html += "<span class='bg-green-500 text-white px-2 py-1 rounded'>#{after_value}</span>"
        end
        
        changes_html += "</li>"
        changes_html += "</ul>"
      end

      changes_html.html_safe

    else
      "Sem alterações registradas"
    end
  end

  def format_event_type(event_type)
    case event_type
    when "update"
      "<span class='text-green-600'>Atualização</span>".html_safe
    when "create"
      "<span class='text-blue-600'>Criação</span>".html_safe
    else
      "<span class='text-red-600'>Remoção</span>".html_safe
    end
  end
end

app/views/medicines/_form.html.erb
<%= simple_form_for(@medicine, html: { class: "contents" }) do |form| %>
  <% if @medicine.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@medicine.errors.count, "error") %> proibiram esse remédio de ser salvo:</h2>

      <ul>
        <% @medicine.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <p class="text-slate-900 font-medium text-sm">Imagem</p>
    <%= form.file_field :picture, label: "Imagem", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full dark:text-slate-900" %>
  </div>

  <div class="my-5 text-slate-900">
    <%= form.input :name, label: "Nome", input_html: { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="my-5 text-slate-900 relative">
    <label for="<%= form.object_name %>_unit" class="block text-slate-900 mb-2  font-medium text-sm">
      Unidade
      <span class="relative group inline-block">
        <%= lucide_icon('info', class: 'inline-block w-4 h-4 text-blue-600 cursor-pointer ml-1') %>
        <div class="absolute bottom-full left-1/2 transform -translate-x-1/2 mb-2 hidden group-hover:block bg-gray-800 text-white text-sm rounded-lg py-1 px-2">
          Quantidade de cartela/frasco do remédio em estoque.
        </div>
      </span>
    </label>
    <%= form.input :unit, as: :integer, label: false, input_html: { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full text-slate-900" } %>
  </div>

  <div class="my-5 text-slate-900">
    <%= form.input :is_liquid, as: :radio_buttons, label: "É liquido?", input_html: { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2" } %>
  </div>

  <div class="my-5 text-slate-900 relative">
    <label class="block text-slate-900 mb-2 font-medium text-sm">
      Quantidade
      <span class="relative group inline-block">
        <%= lucide_icon('info', class: 'inline-block w-4 h-4 text-blue-600 cursor-pointer ml-1') %>
        <div class="absolute bottom-full left-1/2 transform -translate-x-1/2 mb-2 hidden group-hover:block bg-gray-800 text-white text-sm rounded-lg py-1 px-2">
          Quantidade de comprimidos (ou ml se for líquido) em uma unidade. Exemplo: Benegripe possue 6 comprimidos em uma unidade.
        </div>
      </span>
    </label>
    <%= form.input :quantity, as: :integer, label: false, input_html: { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full text-slate-900" } %>
  </div>

  <div class="my-5 text-slate-900">
    <%= form.input :description, as: :text, label: "Descrição", input_html: { rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full text-slate-900" } %>
  </div>

  <div class="my-5 text-slate-900">
    <%= form.label :medicine_validity, "Validade", class: "font-medium text-sm" %>
    <%= form.date_field :medicine_validity, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full text-slate-900" %>
  </div>

  <div class="my-5 text-slate-900">
    <%= form.label :medicine_insert, "Bula", class: "block text-slate-900 mb-2 font-medium text-sm dark:text-slate-900" %>
    <%= form.file_field :medicine_insert, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full text-slate-900" %>
  </div>

  <div class="my-5 text-slate-900 relative">
    <label class="block text-slate-900 mb-2 font-medium text-sm">
      Usado para
      <span class="relative group inline-block">
        <%= lucide_icon('info', class: 'inline-block w-4 h-4 text-blue-600 cursor-pointer ml-1') %>
        <div class="absolute bottom-full left-1/2 transform -translate-x-1/2 mb-2 hidden group-hover:block bg-gray-800 text-white text-sm rounded-lg py-1 px-2">
          Para que é ou foi utilizado o remédio.
        </div>
      </span>
    </label>
    <%= form.input :used_to, label: false, input_html: { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full text-slate-900" } %>
  </div>

  <div class="my-5 text-slate-900">
    <%= form.association :symptoms, as: :check_boxes, collection: Symptom.all, label: "Sintomas", checked: @medicine.symptom_ids %>
  </div>

  <div class="inline">
    <%= form.button :submit, @medicine.new_record? ? "Cadastrar" : "Editar", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/medicines/_form.turbo_stream.erb
<%= simple_form_for(@medicine, html: { class: "contents" }) do |form| %>
  <% if @medicine.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@medicine.errors.count, "error") %> proibiram esse remédio de ser salvo:</h2>

      <ul>
        <% @medicine.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <p class="text-slate-900 font-medium text-sm">Imagem</p>
    <%= form.file_field :picture, label: "Imagem", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full dark:text-slate-900" %>
  </div>

  <div class="my-5 text-slate-900">
    <%= form.input :name, label: "Nome", input_html: { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="my-5 text-slate-900 relative">
    <label for="<%= form.object_name %>_unit" class="block text-slate-900 mb-2  font-medium text-sm">
      Unidade
      <span class="relative group inline-block">
        <%= lucide_icon('info', class: 'inline-block w-4 h-4 text-blue-600 cursor-pointer ml-1') %>
        <div class="absolute bottom-full left-1/2 transform -translate-x-1/2 mb-2 hidden group-hover:block bg-gray-800 text-white text-sm rounded-lg py-1 px-2">
          Quantidade de cartela/frasco do remédio em estoque.
        </div>
      </span>
    </label>
    <%= form.input :unit, as: :integer, label: false, input_html: { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full text-slate-900" } %>
  </div>

  <div class="my-5 text-slate-900">
    <%= form.input :is_liquid, as: :radio_buttons, label: "É liquido?", input_html: { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2" } %>
  </div>

  <div class="my-5 text-slate-900 relative">
    <label class="block text-slate-900 mb-2 font-medium text-sm">
      Quantidade
      <span class="relative group inline-block">
        <%= lucide_icon('info', class: 'inline-block w-4 h-4 text-blue-600 cursor-pointer ml-1') %>
        <div class="absolute bottom-full left-1/2 transform -translate-x-1/2 mb-2 hidden group-hover:block bg-gray-800 text-white text-sm rounded-lg py-1 px-2">
          Quantidade de comprimidos (ou ml se for líquido) em uma unidade. Exemplo: Benegripe possue 6 comprimidos em uma unidade.
        </div>
      </span>
    </label>
    <%= form.input :quantity, as: :integer, label: false, input_html: { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full text-slate-900" } %>
  </div>

  <div class="my-5 text-slate-900">
    <%= form.input :description, as: :text, label: "Descrição", input_html: { rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full text-slate-900" } %>
  </div>

  <div class="my-5 text-slate-900">
    <%= form.label :medicine_validity, "Validade", class: "font-medium text-sm" %>
    <%= form.date_field :medicine_validity, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full text-slate-900" %>
  </div>

  <div class="my-5 text-slate-900">
    <%= form.label :medicine_insert, "Bula", class: "block text-slate-900 mb-2 font-medium text-sm dark:text-slate-900" %>
    <%= form.file_field :medicine_insert, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full text-slate-900" %>
  </div>

  <div class="my-5 text-slate-900 relative">
    <label class="block text-slate-900 mb-2 font-medium text-sm">
      Usado para
      <span class="relative group inline-block">
        <%= lucide_icon('info', class: 'inline-block w-4 h-4 text-blue-600 cursor-pointer ml-1') %>
        <div class="absolute bottom-full left-1/2 transform -translate-x-1/2 mb-2 hidden group-hover:block bg-gray-800 text-white text-sm rounded-lg py-1 px-2">
          Para que é ou foi utilizado o remédio.
        </div>
      </span>
    </label>
    <%= form.input :used_to, label: false, input_html: { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full text-slate-900" } %>
  </div>

  <div class="my-5 text-slate-900">
    <%= form.association :symptoms, as: :check_boxes, collection: Symptom.all, label: "Sintomas", checked: @medicine.symptom_ids %>
  </div>

  <div class="inline">
    <%= form.button :submit, @medicine.new_record? ? "Cadastrar" : "Editar", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/medicines/_modal.turbo_stream.erb
<%= turbo_frame_tag "modal" do %>
  <div class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 z-50 transition-opacity duration-300 opacity-0 pointer-events-none" data-controller="modal" data-modal-target="modal" data-action="click->modal#closeWithBackdrop">
    <div class="bg-white rounded-lg overflow-hidden shadow-xl transform transition-all sm:max-w-lg sm:w-full max-h-90vh" data-modal-target="dialog" data-action="click->modal#stopPropagation">
      <div class="bg-blue-500 px-4 py-3 sm:px-6 flex justify-between items-center">
        <h5 class="text-lg leading-6 font-medium text-white"><%= title %></h5>
        <button type="button" class="text-white" data-action="modal#close" aria-label="Close">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="px-4 py-5 sm:p-6 overflow-y-auto" style="max-height: 90vh;" id="modal_body">
        <%= yield %>
      </div>
    </div>
  </div>
<% end %>

app/views/medicines/activities.html.erb
<% content_for :title, "Atividades" %>

<div class="flex justify-between items-center mb-6">
  <h1 class="font-bold text-4xl text-blue-500">Atividades</h1>
</div>

<div id="activities" class="w-full">
  <% if @activities.any? %>
    <table class="min-w-full divide-y divide-gray-200 dark:bg-gray-900">
      <thead class="bg-blue-50 dark:bg-gray-700">
        <tr>
          <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">ID do remédio</th>
          <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">Evento</th>
          <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">Data da alteração</th>
          <% if current_profile.role == 'admin' %>
            <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">Usuário</th>
          <% end %>
          <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">Alteração</th>
        </tr>
      </thead>
      <tbody class="bg-white dark:bg-slate-700 divide-y divide-gray-200 dark:divide-gray-600">
        <% @activities.each do |activity| %>
          <tr id="<%= dom_id activity %>">
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm dark:text-blue-50 text-gray-900"><%= activity.item_id %></div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm dark:text-blue-50 text-gray-900"><%= format_event_type(activity.event) %></div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm dark:text-blue-50 text-gray-900"><%= activity.created_at.strftime("%d/%m/%Y - %H:%M") %></div>
            </td>
            <% if current_profile.role == 'admin' %>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm dark:text-blue-50 text-gray-900">
                  <% profile = Profile.find_by_id(activity.whodunnit) %>
                  <% unless profile.nil? %>
                    <%= profile.email %>
                  <% end %>
                </div>
              </td>
            <% end %>
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm dark:text-blue-50 text-gray-900"><%= format_changes(activity.object_changes, activity.event) %></div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Nenhuma atividade registrada</p>
  <% end %> 
</div>

app/views/medicines/edit.html.erb
<%= render "modal", title: "Editar remédio" do %>
  <div class="mx-auto w-full">
    <div class="bg-white">
      <%= render "form", medicine: @medicine %>
    </div>
  </div>
<% end %>

app/views/medicines/edit.turbo_stream.erb
<%= render "modal", title: "Editar remédio" do %>
  <div class="mx-auto w-full">
    <div class="bg-white">
      <%= render "form", medicine: @medicine %>
    </div>
  </div>
<% end %>

app/views/medicines/index.html.erb
<% content_for :title, "Remédios" %>

<div class="flex justify-between items-center mb-6">
  <h1 class="font-bold text-4xl text-blue-500">Remédios</h1>
  <%= link_to "Cadastrar remédio", new_medicine_path, class: "rounded-lg py-3 px-5 bg-blue-400 hover:bg-blue-500 text-white block font-medium", data: { turbo_frame: "modal" } %>
</div>

<div id="medicines" class="w-full">
  <% if @medicines.any? %>
    <table class="min-w-full divide-y divide-gray-200 dark:bg-gray-900">
      <thead class="bg-blue-50 dark:bg-gray-700">
        <tr>
          <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">Nome</th>
          <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">Unidade(s)</th>
          <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">É liquido?</th>
          <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">Quantidade</th>
          <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">Validade</th>
          <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">Sintomas</th>
          <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">Usado para</th>
          <% if current_profile.role == 'admin' %>
            <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">Usuário</th>
          <% end %>
          <th class="px-6 py-3 text-left text-xs font-medium dark:text-blue-50 text-gray-500 uppercase tracking-wider">Ações</th>
        </tr>
      </thead>
      <tbody class="bg-white dark:bg-slate-700 divide-y divide-gray-200 dark:divide-gray-600">
        <% @medicines.each do |medicine| %>
          <tr id="<%= dom_id medicine %>">
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm dark:text-blue-50 text-gray-900"><%= medicine.name %></div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm dark:text-blue-50 text-gray-900"><%= medicine.unit %></div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm dark:text-blue-50 text-gray-900">
                <% if medicine.is_liquid %>
                  <%= lucide_icon('circle-check', class: 'text-green-600') %>
                <% else %>
                  <%= lucide_icon('circle-minus', class: 'text-orange-400') %>
                <% end %>
                
              </div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm dark:text-blue-50 text-gray-900"><%= medicine.quantity %></div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm dark:text-blue-50 text-gray-900"><%= medicine.medicine_validity.strftime("%d/%m/%Y") %></div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm dark:text-blue-50 text-gray-900">
                <% medicine.symptoms.each do |symptom| %>
                  <span class="inline-block bg-yellow-400 text-white text-sm px-3 py-1 rounded-md">
                    <%= symptom.name %>
                  </span>
                <% end %>
              </div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm dark:text-blue-50 text-gray-900"><%= medicine.used_to %></div>
            </td>
            <% if current_profile.role == 'admin' %>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm dark:text-blue-50 text-gray-900"><%= medicine.profile.name %></div>
              </td>
            <% end %>
            <td class="px-6 py-4 whitespace-nowrap text-left text-sm font-medium">
              <%= link_to medicine, class: "ml-2 rounded-lg py-2 px-4 text-blue-600 hover:bg-gray-100 inline-block font-medium cursor-pointer", data: { turbo_frame: "modal" } do %>
                <%= lucide_icon('eye', class: 'inline-block text-blue-600 cursor-pointer') %>
              <% end %>
              <%= link_to edit_medicine_path(medicine), class: "ml-2 rounded-lg py-2 px-4 text-blue-600 hover:bg-gray-100 inline-block font-medium cursor-pointer", data: { turbo_frame: "modal" } do %>
                <%= lucide_icon('file-pen-line', class: 'inline-block text-blue-600 cursor-pointer') %>
              <% end %>
              <%= link_to medicine, method: :delete, class: "ml-2 rounded-lg py-2 px-4 text-blue-600 hover:bg-gray-100 inline-block font-medium cursor-pointer", data: { turbo_method: :delete, turbo_confirm: "Tem certeza?" } do %>
                <%= lucide_icon('circle-x', class: 'inline-block text-red-600 cursor-pointer') %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Nenhum remédio registrado</p>
  <% end %>
</div>

app/views/medicines/new.html.erb
<%= render "modal", title: "Cadastrar novo remédio" do %>
  <div class="mx-auto w-full">
    <div class="bg-white">
      <%= render "form", medicine: @medicine %>
    </div>
  </div>
<% end %>

app/views/medicines/new.turbo_stream.erb
<%= render "modal", title: "Cadastrar novo remédio" do %>
  <div class="mx-auto w-full">
    <div class="bg-white">
      <%= render "form", medicine: @medicine %>
    </div>
  </div>
<% end %>