config/routes.rb
Rails.application.routes.draw do
  resources :members
  devise_for :profiles, controllers: { registrations: 'profiles/registrations' }
  resources :profiles, except: [:new, :create, :show]
  get 'profiles/new', to: 'profiles#new', as: :new_profile
  post 'profiles_management', to: 'profiles#create', as: :create_profile

  resources :symptoms
  resources :medicines do
    get :activities, on: :collection
  end
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_profile.role != "admin"
      @medicine = Medicine.where(profile_id: current_profile.id)
      @symptom = Symptom.all
      @expiring_medicines = current_profile.medicines.where("medicine_validity <= ?", 10.days.from_now).order(:medicine_validity)
    else
      @medicine = Medicine.all
      @symptom = Symptom.all
      @expiring_medicines = Medicine.where("medicine_validity <= ?", 10.days.from_now).order(:medicine_validity)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% content_for :title, "Página inicial" %>

<div class="flex justify-between items-center mb-6">
  <h1 class="font-bold text-4xl text-blue-500">Medicare</h1>
</div>

<div id="home" class="w-full">

  <% if @medicine.last == nil and @symptom.last == nil %>
    <p>
      Seja bem vindo a Medicare. Sua farmacinha particular e online!
      No momento você não tem nada cadastrado no sistema.

      <p>Para começar a usar a Medicare comece cadastrando um sintoma <%= link_to "aqui", new_symptom_path, class: "text-blue-500 underline" %></p>
    </p>
  <% else %>  
    <p>Lista de remédios que tenho em casa | Atualizado em:
      <span class="bg-slate-500 text-white px-2 py-1 rounded">
        <%= @medicine.last ? @medicine.last.updated_at.strftime("%d/%m/%Y") : "---" %>
      </span> 
    </p>

    <br />

    <div class="flex flex-wrap">
      <div class="w-full md:w-1/3 px-2">
        <%= link_to medicines_path, class: "block w-full text-center py-2 bg-blue-500 text-white rounded shadow-md" do %>
          Remédios registrados
          <span class="ml-2 bg-gray-500 text-white px-2 py-1 rounded">
            <%= @medicine.count %>
          </span>
        <% end %>
      </div>
      <div class="w-full md:w-1/3 px-2">
        <%= link_to symptoms_path, class: "block w-full text-center py-2 bg-blue-300 text-white rounded shadow-md" do %>
          Sintomas registrados
          <span class="ml-2 bg-gray-500 text-white px-2 py-1 rounded">
            <%= @symptom.count %>
          </span>
        <% end %>
      </div>
      <div class="w-full md:w-1/3 px-2">
        <button type="button" class="block w-full text-center py-2 bg-yellow-500 text-white rounded shadow-md cursor-not-allowed">
          Próximo ao vencimento
          <span class="ml-2 bg-gray-500 text-white px-2 py-1 rounded">
            <%= @expiring_medicines.count %>
          </span>
        </button>
        <% if @expiring_medicines.any? %>
          <ul class="mt-2">
            <% @expiring_medicines.each do |medicine| %>
              <li><%= "#{medicine.name} - Vencimento em #{medicine.medicine_validity.strftime("%d/%m/%Y")}" %></li>
            <% end %>
          </ul>
        <% else %>
          <p class="text-gray-700 mt-2">Nenhum medicamento próximo ao vencimento.</p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>