config/routes.rb
Rails.application.routes.draw do
  resources :members
  devise_for :profiles, controllers: { registrations: 'profiles/registrations' }
  resources :profiles, except: [:new, :create, :show]
  get 'profiles/new', to: 'profiles#new', as: :new_profile
  post 'profiles_management', to: 'profiles#create', as: :create_profile

  resources :symptoms
  resources :medicines do
    get :activities, on: :collection
  end
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Medicare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'rails_toastify', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'rails_toastify', 'data-turbo-track': 'reload' %>

    <%= javascript_importmap_tags %>
  </head>

  <body data-controller="theme">
    <% if profile_signed_in? %>
      <div class="flex h-screen overflow-hidden">
        <aside data-controller="sidebar" data-sidebar-target="sidebar" class="bg-blue-500 text-white dark:bg-slate-700 w-60 space-y-6 py-7 px-2 fixed inset-y-0 left-0 transform -translate-x-full md:relative md:translate-x-0 transition-transform duration-200 ease-in-out">
          <div class="flex items-center justify-between px-4">
            <div id="logo" class="flex items-center space-x-2">
              <span class="text-3xl font-bold" data-sidebar-target="logo"><%= lucide_icon('briefcase-medical', class: 'h-10 w-10') %></span>
              <span class="text-3xl font-bold hidden md:block" data-sidebar-target="fullLogo">Medicare</span>
            </div>
            <button data-action="sidebar#toggle" class="text-white md:hidden focus:outline-none">
              <%= lucide_icon('menu', class: 'h-6 w-6') %>
            </button>
          </div>
          <nav>
            <%= link_to root_path, class: "block py-2.5 px-4 rounded transition duration-200 hover:bg-blue-700" do %>
              <%= lucide_icon('home', class: 'h-6 w-6 inline-block') %>
              <span class="ml-3 hidden md:inline">Home</span>
            <% end %>
            <%= link_to medicines_path, class: "block py-2.5 px-4 rounded transition duration-200 hover:bg-blue-700" do %>
              <%= lucide_icon('pill', class: 'h-6 w-6 inline-block') %>
              <span class="ml-3 hidden md:inline">Remédios</span>
            <% end %>
            <%= link_to symptoms_path, class: "block py-2.5 px-4 rounded transition duration-200 hover:bg-blue-700" do %>
              <%= lucide_icon('thermometer', class: 'h-6 w-6 inline-block') %>
              <span class="ml-3 hidden md:inline">Sintomas</span>
            <% end %>
            <%= link_to members_path, class: "block py-2.5 px-4 rounded transition duration-200 hover:bg-blue-700" do %>
              <%= lucide_icon('user-round-plus', class: 'h-6 w-6 inline-block') %>
              <span class="ml-3 hidden md:inline">Membros</span>
            <% end %>
            <%= link_to activities_medicines_path, class: "block py-2.5 px-4 rounded transition duration-200 hover:bg-blue-700" do %>
              <%= lucide_icon('history', class: 'h-6 w-6 inline-block') %>
              <span class="ml-3 hidden md:inline">Atividades</span>
            <% end %>
            <% if current_profile.role == 'admin' %>
              <%= link_to profiles_path, class: "block py-2.5 px-4 rounded transition duration-200 hover:bg-blue-700" do %>
                <%= lucide_icon('users', class: 'h-6 w-6 inline-block') %>
                <span class="ml-3 hidden md:inline">Perfils</span>
              <% end %>
            <% end %>
          </nav>
        </aside>

        <div class="flex-1 flex flex-col">
          <header class="bg-white shadow-md py-4 px-8 flex justify-between items-center dark:bg-gray-800 dark:text-white">
            <button data-action="theme#toggle" class="text-slate-400 hover:text-slate-600 dark:text-white">
              <%= lucide_icon('moon', class: 'h-6 w-6 inline-block dark:hidden') %>
              <%= lucide_icon('sun', class: 'h-6 w-6 inline-block hidden dark:block') %>
            </button>
            <div class="flex items-center space-x-4">   
              <span class="text-slate-700 dark:text-white">Olá, <%= current_profile.name %> (<%= current_profile.email %>)</span>
              <%= form_tag destroy_profile_session_path, method: :delete, class: "inline" do %>
                <button type="submit" class="text-slate-400 hover:text-slate-600 dark:text-white flex items-center space-x-2">
                  <%= lucide_icon('log-out', class: 'h-6 w-6 inline-block') %>
                  <span>Sair</span>
                </button>
              <% end %>
            </div>
          </header>
          <main class="flex-1 overflow-auto p-8 dark:bg-gray-900 dark:text-white">
            <button data-action="sidebar#toggle" class="fixed bottom-4 left-4 bg-blue-600 text-white p-2 rounded-full shadow-md hover:bg-blue-700 dark:bg-slate-700 dark:text-white">
              <%= lucide_icon('arrow-left', class: 'h-6 w-6') %>
            </button>
            <%= rails_toastify_container %>
            <%= rails_toastify_script %>

            <%= yield %>
            <%= turbo_frame_tag "modal", target: "_top" %>
          </main>
        </div>
      </div>
    <% else %>
      <%= yield %>
    <% end %>

    <% if notice %>
      <script>
        RailsToastify.show('<%= notice %>',
          { theme: '<%= RailsToastify.configuration.notice_theme %>',
            type: '<%= RailsToastify.configuration.notice_type %>',
            animation: '<%= RailsToastify.configuration.notice_animation %>',
            duration: <%= RailsToastify.configuration.notice_duration %>
          })
      </script>
    <% end %>

    <% if alert %>
      <script>
        RailsToastify.show('<%= alert %>',
          { theme: '<%= RailsToastify.configuration.alert_theme %>',
            type: '<%= RailsToastify.configuration.alert_type %>',
            animation: '<%= RailsToastify.configuration.alert_animation %>',
            duration: <%= RailsToastify.configuration.alert_duration %>
          })
      </script>
    <% end %>
  </body>
</html>